from typing import Protocol, Iterable

from ..models import NormalizedRecord, RecordError


class RecordIndex(Protocol):
    def insert(self, side: str, record: NormalizedRecord | RecordError, eligible: bool) -> None: ...
    def groups(self) -> Iterable[tuple]: ...
    def occurrences(self, key: str, side: str) -> Iterable[dict]: ...
    def add_evidence(self, evidence: dict) -> None: ...
    def evidence(self) -> Iterable[dict]: ...
    def errors(self) -> Iterable[dict]: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
